/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtokolleRouteRouteImport } from './routes/protokolle/route'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ProtokolleIndexRouteImport } from './routes/protokolle/index'
import { Route as ProtokolleIdRouteImport } from './routes/protokolle/$id'
import { Route as ProtokolleAuditRouteImport } from './routes/protokolle/audit'
import { Route as ProtokolleEinstellungenRouteImport } from './routes/protokolle/einstellungen'
import { Route as ProtokolleExportRouteImport } from './routes/protokolle/export'
import { Route as ProtokolleNeuRouteImport } from './routes/protokolle/neu'
import { Route as ProtokolleUmsaetzeRouteImport } from './routes/protokolle/umsaetze'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiExportJsonRouteImport } from './routes/api/export.json'
import { Route as ApiExportRevenueRouteImport } from './routes/api/export.revenue'
import { Route as ApiExportUstRouteImport } from './routes/api/export.ust'
import { Route as ApiImportHistoricalProtocolsRouteImport } from './routes/api/import.historical-protocols'
import { Route as ApiImportHistoricalSourcesRouteImport } from './routes/api/import.historical-sources'
import { Route as ApiImportRevenueRouteImport } from './routes/api/import.revenue'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiExportRevenueXlsxRouteImport } from './routes/api/export.revenue.xlsx'
import { Route as ApiHistoricalRevenuesIdSourceRouteImport } from './routes/api/historical-revenues/$id/source'
import { Route as ApiImportRevenueTemplateRouteImport } from './routes/api/import.revenue.template'
import { Route as ApiProtokolleIdPdfRouteImport } from './routes/api/protokolle/$id/pdf'
import { Route as ApiProtokolleIdStornoPdfRouteImport } from './routes/api/protokolle/$id/storno-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtokolleRouteRoute = ProtokolleRouteRouteImport.update({
  id: '/protokolle',
  path: '/protokolle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtokolleIndexRoute = ProtokolleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ProtokolleIdRoute = ProtokolleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ProtokolleAuditRoute = ProtokolleAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ProtokolleEinstellungenRoute = ProtokolleEinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ProtokolleExportRoute = ProtokolleExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ProtokolleNeuRoute = ProtokolleNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ProtokolleUmsaetzeRoute = ProtokolleUmsaetzeRouteImport.update({
  id: '/umsaetze',
  path: '/umsaetze',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportJsonRoute = ApiExportJsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => ApiExportRoute,
} as any)
const ApiExportRevenueRoute = ApiExportRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => ApiExportRoute,
} as any)
const ApiExportUstRoute = ApiExportUstRouteImport.update({
  id: '/ust',
  path: '/ust',
  getParentRoute: () => ApiExportRoute,
} as any)
const ApiImportHistoricalProtocolsRoute =
  ApiImportHistoricalProtocolsRouteImport.update({
    id: '/api/import/historical-protocols',
    path: '/api/import/historical-protocols',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiImportHistoricalSourcesRoute =
  ApiImportHistoricalSourcesRouteImport.update({
    id: '/api/import/historical-sources',
    path: '/api/import/historical-sources',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiImportRevenueRoute = ApiImportRevenueRouteImport.update({
  id: '/api/import/revenue',
  path: '/api/import/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRevenueXlsxRoute = ApiExportRevenueXlsxRouteImport.update({
  id: '/xlsx',
  path: '/xlsx',
  getParentRoute: () => ApiExportRevenueRoute,
} as any)
const ApiHistoricalRevenuesIdSourceRoute =
  ApiHistoricalRevenuesIdSourceRouteImport.update({
    id: '/api/historical-revenues/$id/source',
    path: '/api/historical-revenues/$id/source',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiImportRevenueTemplateRoute =
  ApiImportRevenueTemplateRouteImport.update({
    id: '/template',
    path: '/template',
    getParentRoute: () => ApiImportRevenueRoute,
  } as any)
const ApiProtokolleIdPdfRoute = ApiProtokolleIdPdfRouteImport.update({
  id: '/api/protokolle/$id/pdf',
  path: '/api/protokolle/$id/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtokolleIdStornoPdfRoute =
  ApiProtokolleIdStornoPdfRouteImport.update({
    id: '/api/protokolle/$id/storno-pdf',
    path: '/api/protokolle/$id/storno-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/protokolle': typeof ProtokolleRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/export': typeof ApiExportRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/invite/$token': typeof InviteTokenRoute
  '/protokolle/$id': typeof ProtokolleIdRoute
  '/protokolle/audit': typeof ProtokolleAuditRoute
  '/protokolle/einstellungen': typeof ProtokolleEinstellungenRoute
  '/protokolle/export': typeof ProtokolleExportRoute
  '/protokolle/neu': typeof ProtokolleNeuRoute
  '/protokolle/umsaetze': typeof ProtokolleUmsaetzeRoute
  '/protokolle/': typeof ProtokolleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/export/json': typeof ApiExportJsonRoute
  '/api/export/revenue': typeof ApiExportRevenueRouteWithChildren
  '/api/export/ust': typeof ApiExportUstRoute
  '/api/import/historical-protocols': typeof ApiImportHistoricalProtocolsRoute
  '/api/import/historical-sources': typeof ApiImportHistoricalSourcesRoute
  '/api/import/revenue': typeof ApiImportRevenueRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/export/revenue/xlsx': typeof ApiExportRevenueXlsxRoute
  '/api/historical-revenues/$id/source': typeof ApiHistoricalRevenuesIdSourceRoute
  '/api/import/revenue/template': typeof ApiImportRevenueTemplateRoute
  '/api/protokolle/$id/pdf': typeof ApiProtokolleIdPdfRoute
  '/api/protokolle/$id/storno-pdf': typeof ApiProtokolleIdStornoPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/export': typeof ApiExportRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/invite/$token': typeof InviteTokenRoute
  '/protokolle/$id': typeof ProtokolleIdRoute
  '/protokolle/audit': typeof ProtokolleAuditRoute
  '/protokolle/einstellungen': typeof ProtokolleEinstellungenRoute
  '/protokolle/export': typeof ProtokolleExportRoute
  '/protokolle/neu': typeof ProtokolleNeuRoute
  '/protokolle/umsaetze': typeof ProtokolleUmsaetzeRoute
  '/protokolle': typeof ProtokolleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/export/json': typeof ApiExportJsonRoute
  '/api/export/revenue': typeof ApiExportRevenueRouteWithChildren
  '/api/export/ust': typeof ApiExportUstRoute
  '/api/import/historical-protocols': typeof ApiImportHistoricalProtocolsRoute
  '/api/import/historical-sources': typeof ApiImportHistoricalSourcesRoute
  '/api/import/revenue': typeof ApiImportRevenueRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/export/revenue/xlsx': typeof ApiExportRevenueXlsxRoute
  '/api/historical-revenues/$id/source': typeof ApiHistoricalRevenuesIdSourceRoute
  '/api/import/revenue/template': typeof ApiImportRevenueTemplateRoute
  '/api/protokolle/$id/pdf': typeof ApiProtokolleIdPdfRoute
  '/api/protokolle/$id/storno-pdf': typeof ApiProtokolleIdStornoPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/protokolle': typeof ProtokolleRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/export': typeof ApiExportRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/mcp': typeof ApiMcpRoute
  '/invite/$token': typeof InviteTokenRoute
  '/protokolle/$id': typeof ProtokolleIdRoute
  '/protokolle/audit': typeof ProtokolleAuditRoute
  '/protokolle/einstellungen': typeof ProtokolleEinstellungenRoute
  '/protokolle/export': typeof ProtokolleExportRoute
  '/protokolle/neu': typeof ProtokolleNeuRoute
  '/protokolle/umsaetze': typeof ProtokolleUmsaetzeRoute
  '/protokolle/': typeof ProtokolleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/export/json': typeof ApiExportJsonRoute
  '/api/export/revenue': typeof ApiExportRevenueRouteWithChildren
  '/api/export/ust': typeof ApiExportUstRoute
  '/api/import/historical-protocols': typeof ApiImportHistoricalProtocolsRoute
  '/api/import/historical-sources': typeof ApiImportHistoricalSourcesRoute
  '/api/import/revenue': typeof ApiImportRevenueRouteWithChildren
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/export/revenue/xlsx': typeof ApiExportRevenueXlsxRoute
  '/api/historical-revenues/$id/source': typeof ApiHistoricalRevenuesIdSourceRoute
  '/api/import/revenue/template': typeof ApiImportRevenueTemplateRoute
  '/api/protokolle/$id/pdf': typeof ApiProtokolleIdPdfRoute
  '/api/protokolle/$id/storno-pdf': typeof ApiProtokolleIdStornoPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/protokolle'
    | '/login'
    | '/api/export'
    | '/api/health'
    | '/api/mcp'
    | '/invite/$token'
    | '/protokolle/$id'
    | '/protokolle/audit'
    | '/protokolle/einstellungen'
    | '/protokolle/export'
    | '/protokolle/neu'
    | '/protokolle/umsaetze'
    | '/protokolle/'
    | '/api/auth/$'
    | '/api/export/json'
    | '/api/export/revenue'
    | '/api/export/ust'
    | '/api/import/historical-protocols'
    | '/api/import/historical-sources'
    | '/api/import/revenue'
    | '/api/rpc/$'
    | '/api/export/revenue/xlsx'
    | '/api/historical-revenues/$id/source'
    | '/api/import/revenue/template'
    | '/api/protokolle/$id/pdf'
    | '/api/protokolle/$id/storno-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/export'
    | '/api/health'
    | '/api/mcp'
    | '/invite/$token'
    | '/protokolle/$id'
    | '/protokolle/audit'
    | '/protokolle/einstellungen'
    | '/protokolle/export'
    | '/protokolle/neu'
    | '/protokolle/umsaetze'
    | '/protokolle'
    | '/api/auth/$'
    | '/api/export/json'
    | '/api/export/revenue'
    | '/api/export/ust'
    | '/api/import/historical-protocols'
    | '/api/import/historical-sources'
    | '/api/import/revenue'
    | '/api/rpc/$'
    | '/api/export/revenue/xlsx'
    | '/api/historical-revenues/$id/source'
    | '/api/import/revenue/template'
    | '/api/protokolle/$id/pdf'
    | '/api/protokolle/$id/storno-pdf'
  id:
    | '__root__'
    | '/'
    | '/protokolle'
    | '/login'
    | '/api/export'
    | '/api/health'
    | '/api/mcp'
    | '/invite/$token'
    | '/protokolle/$id'
    | '/protokolle/audit'
    | '/protokolle/einstellungen'
    | '/protokolle/export'
    | '/protokolle/neu'
    | '/protokolle/umsaetze'
    | '/protokolle/'
    | '/api/auth/$'
    | '/api/export/json'
    | '/api/export/revenue'
    | '/api/export/ust'
    | '/api/import/historical-protocols'
    | '/api/import/historical-sources'
    | '/api/import/revenue'
    | '/api/rpc/$'
    | '/api/export/revenue/xlsx'
    | '/api/historical-revenues/$id/source'
    | '/api/import/revenue/template'
    | '/api/protokolle/$id/pdf'
    | '/api/protokolle/$id/storno-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtokolleRouteRoute: typeof ProtokolleRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiExportRoute: typeof ApiExportRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMcpRoute: typeof ApiMcpRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiImportHistoricalProtocolsRoute: typeof ApiImportHistoricalProtocolsRoute
  ApiImportHistoricalSourcesRoute: typeof ApiImportHistoricalSourcesRoute
  ApiImportRevenueRoute: typeof ApiImportRevenueRouteWithChildren
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiHistoricalRevenuesIdSourceRoute: typeof ApiHistoricalRevenuesIdSourceRoute
  ApiProtokolleIdPdfRoute: typeof ApiProtokolleIdPdfRoute
  ApiProtokolleIdStornoPdfRoute: typeof ApiProtokolleIdStornoPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protokolle': {
      id: '/protokolle'
      path: '/protokolle'
      fullPath: '/protokolle'
      preLoaderRoute: typeof ProtokolleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protokolle/': {
      id: '/protokolle/'
      path: '/'
      fullPath: '/protokolle/'
      preLoaderRoute: typeof ProtokolleIndexRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/protokolle/$id': {
      id: '/protokolle/$id'
      path: '/$id'
      fullPath: '/protokolle/$id'
      preLoaderRoute: typeof ProtokolleIdRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/protokolle/audit': {
      id: '/protokolle/audit'
      path: '/audit'
      fullPath: '/protokolle/audit'
      preLoaderRoute: typeof ProtokolleAuditRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/protokolle/einstellungen': {
      id: '/protokolle/einstellungen'
      path: '/einstellungen'
      fullPath: '/protokolle/einstellungen'
      preLoaderRoute: typeof ProtokolleEinstellungenRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/protokolle/export': {
      id: '/protokolle/export'
      path: '/export'
      fullPath: '/protokolle/export'
      preLoaderRoute: typeof ProtokolleExportRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/protokolle/neu': {
      id: '/protokolle/neu'
      path: '/neu'
      fullPath: '/protokolle/neu'
      preLoaderRoute: typeof ProtokolleNeuRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/protokolle/umsaetze': {
      id: '/protokolle/umsaetze'
      path: '/umsaetze'
      fullPath: '/protokolle/umsaetze'
      preLoaderRoute: typeof ProtokolleUmsaetzeRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/json': {
      id: '/api/export/json'
      path: '/json'
      fullPath: '/api/export/json'
      preLoaderRoute: typeof ApiExportJsonRouteImport
      parentRoute: typeof ApiExportRoute
    }
    '/api/export/revenue': {
      id: '/api/export/revenue'
      path: '/revenue'
      fullPath: '/api/export/revenue'
      preLoaderRoute: typeof ApiExportRevenueRouteImport
      parentRoute: typeof ApiExportRoute
    }
    '/api/export/ust': {
      id: '/api/export/ust'
      path: '/ust'
      fullPath: '/api/export/ust'
      preLoaderRoute: typeof ApiExportUstRouteImport
      parentRoute: typeof ApiExportRoute
    }
    '/api/import/historical-protocols': {
      id: '/api/import/historical-protocols'
      path: '/api/import/historical-protocols'
      fullPath: '/api/import/historical-protocols'
      preLoaderRoute: typeof ApiImportHistoricalProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/historical-sources': {
      id: '/api/import/historical-sources'
      path: '/api/import/historical-sources'
      fullPath: '/api/import/historical-sources'
      preLoaderRoute: typeof ApiImportHistoricalSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/revenue': {
      id: '/api/import/revenue'
      path: '/api/import/revenue'
      fullPath: '/api/import/revenue'
      preLoaderRoute: typeof ApiImportRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/revenue/xlsx': {
      id: '/api/export/revenue/xlsx'
      path: '/xlsx'
      fullPath: '/api/export/revenue/xlsx'
      preLoaderRoute: typeof ApiExportRevenueXlsxRouteImport
      parentRoute: typeof ApiExportRevenueRoute
    }
    '/api/historical-revenues/$id/source': {
      id: '/api/historical-revenues/$id/source'
      path: '/api/historical-revenues/$id/source'
      fullPath: '/api/historical-revenues/$id/source'
      preLoaderRoute: typeof ApiHistoricalRevenuesIdSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import/revenue/template': {
      id: '/api/import/revenue/template'
      path: '/template'
      fullPath: '/api/import/revenue/template'
      preLoaderRoute: typeof ApiImportRevenueTemplateRouteImport
      parentRoute: typeof ApiImportRevenueRoute
    }
    '/api/protokolle/$id/pdf': {
      id: '/api/protokolle/$id/pdf'
      path: '/api/protokolle/$id/pdf'
      fullPath: '/api/protokolle/$id/pdf'
      preLoaderRoute: typeof ApiProtokolleIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protokolle/$id/storno-pdf': {
      id: '/api/protokolle/$id/storno-pdf'
      path: '/api/protokolle/$id/storno-pdf'
      fullPath: '/api/protokolle/$id/storno-pdf'
      preLoaderRoute: typeof ApiProtokolleIdStornoPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtokolleRouteRouteChildren {
  ProtokolleIdRoute: typeof ProtokolleIdRoute
  ProtokolleAuditRoute: typeof ProtokolleAuditRoute
  ProtokolleEinstellungenRoute: typeof ProtokolleEinstellungenRoute
  ProtokolleExportRoute: typeof ProtokolleExportRoute
  ProtokolleNeuRoute: typeof ProtokolleNeuRoute
  ProtokolleUmsaetzeRoute: typeof ProtokolleUmsaetzeRoute
  ProtokolleIndexRoute: typeof ProtokolleIndexRoute
}

const ProtokolleRouteRouteChildren: ProtokolleRouteRouteChildren = {
  ProtokolleIdRoute: ProtokolleIdRoute,
  ProtokolleAuditRoute: ProtokolleAuditRoute,
  ProtokolleEinstellungenRoute: ProtokolleEinstellungenRoute,
  ProtokolleExportRoute: ProtokolleExportRoute,
  ProtokolleNeuRoute: ProtokolleNeuRoute,
  ProtokolleUmsaetzeRoute: ProtokolleUmsaetzeRoute,
  ProtokolleIndexRoute: ProtokolleIndexRoute,
}

const ProtokolleRouteRouteWithChildren = ProtokolleRouteRoute._addFileChildren(
  ProtokolleRouteRouteChildren,
)

interface ApiExportRevenueRouteChildren {
  ApiExportRevenueXlsxRoute: typeof ApiExportRevenueXlsxRoute
}

const ApiExportRevenueRouteChildren: ApiExportRevenueRouteChildren = {
  ApiExportRevenueXlsxRoute: ApiExportRevenueXlsxRoute,
}

const ApiExportRevenueRouteWithChildren =
  ApiExportRevenueRoute._addFileChildren(ApiExportRevenueRouteChildren)

interface ApiExportRouteChildren {
  ApiExportJsonRoute: typeof ApiExportJsonRoute
  ApiExportRevenueRoute: typeof ApiExportRevenueRouteWithChildren
  ApiExportUstRoute: typeof ApiExportUstRoute
}

const ApiExportRouteChildren: ApiExportRouteChildren = {
  ApiExportJsonRoute: ApiExportJsonRoute,
  ApiExportRevenueRoute: ApiExportRevenueRouteWithChildren,
  ApiExportUstRoute: ApiExportUstRoute,
}

const ApiExportRouteWithChildren = ApiExportRoute._addFileChildren(
  ApiExportRouteChildren,
)

interface ApiImportRevenueRouteChildren {
  ApiImportRevenueTemplateRoute: typeof ApiImportRevenueTemplateRoute
}

const ApiImportRevenueRouteChildren: ApiImportRevenueRouteChildren = {
  ApiImportRevenueTemplateRoute: ApiImportRevenueTemplateRoute,
}

const ApiImportRevenueRouteWithChildren =
  ApiImportRevenueRoute._addFileChildren(ApiImportRevenueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtokolleRouteRoute: ProtokolleRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiExportRoute: ApiExportRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiMcpRoute: ApiMcpRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiImportHistoricalProtocolsRoute: ApiImportHistoricalProtocolsRoute,
  ApiImportHistoricalSourcesRoute: ApiImportHistoricalSourcesRoute,
  ApiImportRevenueRoute: ApiImportRevenueRouteWithChildren,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiHistoricalRevenuesIdSourceRoute: ApiHistoricalRevenuesIdSourceRoute,
  ApiProtokolleIdPdfRoute: ApiProtokolleIdPdfRoute,
  ApiProtokolleIdStornoPdfRoute: ApiProtokolleIdStornoPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
