/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtokolleRouteRouteImport } from './routes/protokolle/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtokolleIndexRouteImport } from './routes/protokolle/index'
import { Route as ProtokolleNeuRouteImport } from './routes/protokolle/neu'
import { Route as ProtokolleExportRouteImport } from './routes/protokolle/export'
import { Route as ProtokolleEinstellungenRouteImport } from './routes/protokolle/einstellungen'
import { Route as ProtokolleIdRouteImport } from './routes/protokolle/$id'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiExportUstRouteImport } from './routes/api/export.ust'
import { Route as ApiExportJsonRouteImport } from './routes/api/export.json'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProtokolleIdStornoPdfRouteImport } from './routes/api/protokolle/$id/storno-pdf'
import { Route as ApiProtokolleIdPdfRouteImport } from './routes/api/protokolle/$id/pdf'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtokolleRouteRoute = ProtokolleRouteRouteImport.update({
  id: '/protokolle',
  path: '/protokolle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtokolleIndexRoute = ProtokolleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ProtokolleNeuRoute = ProtokolleNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ProtokolleExportRoute = ProtokolleExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ProtokolleEinstellungenRoute = ProtokolleEinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const ProtokolleIdRoute = ProtokolleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProtokolleRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportUstRoute = ApiExportUstRouteImport.update({
  id: '/ust',
  path: '/ust',
  getParentRoute: () => ApiExportRoute,
} as any)
const ApiExportJsonRoute = ApiExportJsonRouteImport.update({
  id: '/json',
  path: '/json',
  getParentRoute: () => ApiExportRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProtokolleIdStornoPdfRoute =
  ApiProtokolleIdStornoPdfRouteImport.update({
    id: '/api/protokolle/$id/storno-pdf',
    path: '/api/protokolle/$id/storno-pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProtokolleIdPdfRoute = ApiProtokolleIdPdfRouteImport.update({
  id: '/api/protokolle/$id/pdf',
  path: '/api/protokolle/$id/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/protokolle': typeof ProtokolleRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/export': typeof ApiExportRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/protokolle/$id': typeof ProtokolleIdRoute
  '/protokolle/einstellungen': typeof ProtokolleEinstellungenRoute
  '/protokolle/export': typeof ProtokolleExportRoute
  '/protokolle/neu': typeof ProtokolleNeuRoute
  '/protokolle/': typeof ProtokolleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/export/json': typeof ApiExportJsonRoute
  '/api/export/ust': typeof ApiExportUstRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/protokolle/$id/pdf': typeof ApiProtokolleIdPdfRoute
  '/api/protokolle/$id/storno-pdf': typeof ApiProtokolleIdStornoPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/export': typeof ApiExportRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/protokolle/$id': typeof ProtokolleIdRoute
  '/protokolle/einstellungen': typeof ProtokolleEinstellungenRoute
  '/protokolle/export': typeof ProtokolleExportRoute
  '/protokolle/neu': typeof ProtokolleNeuRoute
  '/protokolle': typeof ProtokolleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/export/json': typeof ApiExportJsonRoute
  '/api/export/ust': typeof ApiExportUstRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/protokolle/$id/pdf': typeof ApiProtokolleIdPdfRoute
  '/api/protokolle/$id/storno-pdf': typeof ApiProtokolleIdStornoPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/protokolle': typeof ProtokolleRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/api/export': typeof ApiExportRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/invite/$token': typeof InviteTokenRoute
  '/protokolle/$id': typeof ProtokolleIdRoute
  '/protokolle/einstellungen': typeof ProtokolleEinstellungenRoute
  '/protokolle/export': typeof ProtokolleExportRoute
  '/protokolle/neu': typeof ProtokolleNeuRoute
  '/protokolle/': typeof ProtokolleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/export/json': typeof ApiExportJsonRoute
  '/api/export/ust': typeof ApiExportUstRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/protokolle/$id/pdf': typeof ApiProtokolleIdPdfRoute
  '/api/protokolle/$id/storno-pdf': typeof ApiProtokolleIdStornoPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/protokolle'
    | '/login'
    | '/api/export'
    | '/api/health'
    | '/invite/$token'
    | '/protokolle/$id'
    | '/protokolle/einstellungen'
    | '/protokolle/export'
    | '/protokolle/neu'
    | '/protokolle/'
    | '/api/auth/$'
    | '/api/export/json'
    | '/api/export/ust'
    | '/api/rpc/$'
    | '/api/protokolle/$id/pdf'
    | '/api/protokolle/$id/storno-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/export'
    | '/api/health'
    | '/invite/$token'
    | '/protokolle/$id'
    | '/protokolle/einstellungen'
    | '/protokolle/export'
    | '/protokolle/neu'
    | '/protokolle'
    | '/api/auth/$'
    | '/api/export/json'
    | '/api/export/ust'
    | '/api/rpc/$'
    | '/api/protokolle/$id/pdf'
    | '/api/protokolle/$id/storno-pdf'
  id:
    | '__root__'
    | '/'
    | '/protokolle'
    | '/login'
    | '/api/export'
    | '/api/health'
    | '/invite/$token'
    | '/protokolle/$id'
    | '/protokolle/einstellungen'
    | '/protokolle/export'
    | '/protokolle/neu'
    | '/protokolle/'
    | '/api/auth/$'
    | '/api/export/json'
    | '/api/export/ust'
    | '/api/rpc/$'
    | '/api/protokolle/$id/pdf'
    | '/api/protokolle/$id/storno-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtokolleRouteRoute: typeof ProtokolleRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiExportRoute: typeof ApiExportRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiProtokolleIdPdfRoute: typeof ApiProtokolleIdPdfRoute
  ApiProtokolleIdStornoPdfRoute: typeof ApiProtokolleIdStornoPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protokolle': {
      id: '/protokolle'
      path: '/protokolle'
      fullPath: '/protokolle'
      preLoaderRoute: typeof ProtokolleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protokolle/': {
      id: '/protokolle/'
      path: '/'
      fullPath: '/protokolle/'
      preLoaderRoute: typeof ProtokolleIndexRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/protokolle/neu': {
      id: '/protokolle/neu'
      path: '/neu'
      fullPath: '/protokolle/neu'
      preLoaderRoute: typeof ProtokolleNeuRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/protokolle/export': {
      id: '/protokolle/export'
      path: '/export'
      fullPath: '/protokolle/export'
      preLoaderRoute: typeof ProtokolleExportRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/protokolle/einstellungen': {
      id: '/protokolle/einstellungen'
      path: '/einstellungen'
      fullPath: '/protokolle/einstellungen'
      preLoaderRoute: typeof ProtokolleEinstellungenRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/protokolle/$id': {
      id: '/protokolle/$id'
      path: '/$id'
      fullPath: '/protokolle/$id'
      preLoaderRoute: typeof ProtokolleIdRouteImport
      parentRoute: typeof ProtokolleRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/ust': {
      id: '/api/export/ust'
      path: '/ust'
      fullPath: '/api/export/ust'
      preLoaderRoute: typeof ApiExportUstRouteImport
      parentRoute: typeof ApiExportRoute
    }
    '/api/export/json': {
      id: '/api/export/json'
      path: '/json'
      fullPath: '/api/export/json'
      preLoaderRoute: typeof ApiExportJsonRouteImport
      parentRoute: typeof ApiExportRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protokolle/$id/storno-pdf': {
      id: '/api/protokolle/$id/storno-pdf'
      path: '/api/protokolle/$id/storno-pdf'
      fullPath: '/api/protokolle/$id/storno-pdf'
      preLoaderRoute: typeof ApiProtokolleIdStornoPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/protokolle/$id/pdf': {
      id: '/api/protokolle/$id/pdf'
      path: '/api/protokolle/$id/pdf'
      fullPath: '/api/protokolle/$id/pdf'
      preLoaderRoute: typeof ApiProtokolleIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtokolleRouteRouteChildren {
  ProtokolleIdRoute: typeof ProtokolleIdRoute
  ProtokolleEinstellungenRoute: typeof ProtokolleEinstellungenRoute
  ProtokolleExportRoute: typeof ProtokolleExportRoute
  ProtokolleNeuRoute: typeof ProtokolleNeuRoute
  ProtokolleIndexRoute: typeof ProtokolleIndexRoute
}

const ProtokolleRouteRouteChildren: ProtokolleRouteRouteChildren = {
  ProtokolleIdRoute: ProtokolleIdRoute,
  ProtokolleEinstellungenRoute: ProtokolleEinstellungenRoute,
  ProtokolleExportRoute: ProtokolleExportRoute,
  ProtokolleNeuRoute: ProtokolleNeuRoute,
  ProtokolleIndexRoute: ProtokolleIndexRoute,
}

const ProtokolleRouteRouteWithChildren = ProtokolleRouteRoute._addFileChildren(
  ProtokolleRouteRouteChildren,
)

interface ApiExportRouteChildren {
  ApiExportJsonRoute: typeof ApiExportJsonRoute
  ApiExportUstRoute: typeof ApiExportUstRoute
}

const ApiExportRouteChildren: ApiExportRouteChildren = {
  ApiExportJsonRoute: ApiExportJsonRoute,
  ApiExportUstRoute: ApiExportUstRoute,
}

const ApiExportRouteWithChildren = ApiExportRoute._addFileChildren(
  ApiExportRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtokolleRouteRoute: ProtokolleRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiExportRoute: ApiExportRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiProtokolleIdPdfRoute: ApiProtokolleIdPdfRoute,
  ApiProtokolleIdStornoPdfRoute: ApiProtokolleIdStornoPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
